// frontend-vue.ts/src/components/auth/login.vue
<template>
	<div class="login-container">
		<div class="login-content">
			<h1 class="login-title">Login to SpringSocial</h1>
			<div class="social-login">
				<a class="btn btn-block social-btn google" v-bind:href="GOOGLE_AUTH_URL">
					<img src="../../assets/google-logo.png" alt="Google" /> Sign up with Google</a>
				<a class="btn btn-block social-btn facebook" v-bind:href="FACEBOOK_AUTH_URL">
					<img src="../../assets/fb-logo.png" alt="Facebook" /> Sign up with Facebook</a>
				<a class="btn btn-block social-btn facebook" v-bind:href="NAVER_AUTH_URL">
					<img src="../../assets/naver-logo.png" alt="Naver" /> Sign up with naver</a>
				<a class="btn btn-block social-btn facebook" v-bind:href="KAKAO_AUTH_URL">
					<img src="../../assets/kakao-logo.png" alt="Kakao" /> Sign up with kakao</a>
			</div>
			<div class="or-separator">
				<span class="or-text">OR</span>
			</div>
			<form @submit.prevent="login">
				<div class="form-item">
					<input type="email" name="email"
					       class="form-control" placeholder="Email"
					       v-model="user.email"/>
				</div>
				<div class="form-item">
					<input type="password" name="password"
					       class="form-control" placeholder="Password"
					       v-model="user.password"/>
				</div>
				<div class="form-item">
					<button type="submit" class="btn btn-block btn-primary">Login</button>
				</div>
			</form>
			<span class="signup-link">New user? <router-link to="/signup">Sign up!</router-link></span>
		</div>
	</div>
</template>

<script lang="ts">
	import Login from "@/src/auth/login"

	export default Login
</script>

<style scoped>
	.login-container {
		text-align: center;
	}

	.login-content {
		background: #fff;
		box-shadow: 0 1px 11px rgba(0, 0, 0, 0.27);
		border-radius: 2px;
		width: 500px;
		display: inline-block;
		margin-top: 30px;
		vertical-align: middle;
		position: relative;
		padding: 35px;
	}

	.social-btn {
		margin-bottom: 15px;
		font-weight: 400;
		font-size: 16px;
	}

	.social-btn img {
		height: 32px;
		float: left;
		margin-top: 10px;
	}

	.social-btn.google {
		margin-top: 7px;
	}

	.social-btn.facebook img {
		height: 24px;
		margin-left: 3px;
	}

	.social-btn.github img {
		height: 24px;
		margin-left: 3px;
	}

	.signup-link {
		color: rgba(0, 0, 0, 0.65);
		font-size: 14px;
	}

	.login-title {
		font-size: 1.5em;
		font-weight: 500;
		margin-top: 0;
		margin-bottom: 30px;
		color: rgba(0, 0, 0, 0.65);
	}
</style>

// frontend-react/src/user/login/Login.js
import React, { Component } from 'react';
import './Login.css';
import { GOOGLE_AUTH_URL, FACEBOOK_AUTH_URL, NAVER_AUTH_URL, KAKAO_AUTH_URL, ACCESS_TOKEN } from '../../constants';
import { login } from '../../util/APIUtils';
import { Link, Redirect } from 'react-router-dom'
import fbLogo from '../../img/fb-logo.png';
import googleLogo from '../../img/google-logo.png';
import naverLogo from '../../img/naver-logo.png';
import Alert from 'react-s-alert';
import kakaoLogo from "../../img/kakao-logo.png";

class Login extends Component {
    componentDidMount() {
        // If the OAuth2 login encounters an error, the user is redirected to the /login page with an error.
        // Here we display the error and then remove the error query parameter from the location.
        if(this.props.location.state && this.props.location.state.error) {
            setTimeout(() => {
                Alert.error(this.props.location.state.error, {
                    timeout: 5000
                });
                this.props.history.replace({
                    pathname: this.props.location.pathname,
                    state: {}
                });
            }, 100);
        }
    }
    
    render() {
        if(this.props.authenticated) {
            return <Redirect
                to={{
                pathname: "/",
                state: { from: this.props.location }
            }}/>;            
        }

        return (
            <div className="login-container">
                <div className="login-content">
                    <h1 className="login-title">Login to SpringSocial</h1>
                    <SocialLogin />
                    <div className="or-separator">
                        <span className="or-text">OR</span>
                    </div>
                    <LoginForm {...this.props} />
                    <span className="signup-link">New user? <Link to="/signup">Sign up!</Link></span>
                </div>
            </div>
        );
    }
}

class SocialLogin extends Component {
    render() {
        return (
            <div className="social-login">
                <a className="btn btn-block social-btn google" href={GOOGLE_AUTH_URL}>
                    <img src={googleLogo} alt="Google" /> Log in with Google</a>
                <a className="btn btn-block social-btn facebook" href={FACEBOOK_AUTH_URL}>
                    <img src={fbLogo} alt="Facebook" /> Log in with Facebook</a>
                <a className="btn btn-block social-btn facebook" href={NAVER_AUTH_URL}>
                    <img src={naverLogo} alt="Naver" /> Log in with Naver</a>
                <a className="btn btn-block social-btn facebook" href={KAKAO_AUTH_URL}>
                    <img src={kakaoLogo} alt="Github" /> Sign up with kakao</a>
            </div>
        );
    }
}


class LoginForm extends Component {
    constructor(props) {
        super(props);
        this.state = {
            email: '',
            password: ''
        };
        this.handleInputChange = this.handleInputChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    handleInputChange(event) {
        const target = event.target;
        const inputName = target.name;        
        const inputValue = target.value;

        this.setState({
            [inputName] : inputValue
        });        
    }

    handleSubmit(event) {
        event.preventDefault();   

        const loginRequest = Object.assign({}, this.state);

        login(loginRequest)
        .then(response => {
            localStorage.setItem(ACCESS_TOKEN, response.accessToken);
            Alert.success("You're successfully logged in!");
            this.props.history.push("/");
        }).catch(error => {
            Alert.error((error && error.message) || 'Oops! Something went wrong. Please try again!');
        });
    }
    
    render() {
        return (
            <form onSubmit={this.handleSubmit}>
                <div className="form-item">
                    <input type="email" name="email" 
                        className="form-control" placeholder="Email"
                        value={this.state.email} onChange={this.handleInputChange} required/>
                </div>
                <div className="form-item">
                    <input type="password" name="password" 
                        className="form-control" placeholder="Password"
                        value={this.state.password} onChange={this.handleInputChange} required/>
                </div>
                <div className="form-item">
                    <button type="submit" className="btn btn-block btn-primary">Login</button>
                </div>
            </form>                    
        );
    }
}

export default Login
